backend:
  name: git-gateway
  branch: master

media_folder: content/assets
public_folder: ../assets

collections:
#Collections for Pages
  # - name: pages
  #   label: Páginas
  #   folder: content/pages
  #   create: true
  #   fields:
  #     - {label: path, name: path, widget: hidden, default: "index"}
  #     - {label: "Título", name: title, widget: string}
      
  #     - label: "Sessão Como Funciona"
  #       name: feature
  #       widget: "object"
  #       fields:
  #         - {label: "Título", name: title, widget: string}
  #         - {label: "Subtítulo", name: subtitle, widget: string}
      
  #     - label: "Sessão Outros Serviços"
  #       name: service
  #       widget: "object"
  #       fields:
  #         - {label: "Título", name: title, widget: string}
  #         - {label: "Subtítulo", name: subtitle, widget: string}
      
  #     - label: "Contato"
  #       name: contact
  #       widget: "object"
  #       fields:
  #         - {label: "Título", name: title, widget: string}
  #         - {label: "Subtítulo", name: subtitle, widget: text, required: false}

  #     - label: "SEO"
  #       name: seo
  #       widget: "object"
  #       fields:
  #         - {label: "Título", name: title, widget: string}
  #         - {label: "Descrição", name: description, widget: string}

  #     - label: "OpenGraph"
  #       name: opengraph
  #       widget: "object"
  #       fields:
  #         - {label: "Título", name: title, widget: string}
  #         - {label: "Descrição", name: description, widget: string}

  #         - label: "Imagem"
  #           name: image
  #           widget: "object"
  #           fields:
  #             - {label: "Imagem", name: imageUrl, widget: image}
  #             - {label: "Descrição da Imagem", name: imageAlt, widget: string}

  - name: "page"
    label: "Página Inicial"
    files:
      - file: content/pages/index.md
        label: "Págna Inicial"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: SubTitle, name: subtitle, widget: string}
          
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
