backend:
  name: git-gateway
  branch: master

media_folder: content/assets
public_folder: ../assets

collections:
#Collections for Pages
  - label: "Páginas"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Página Inicial"
        name: "index"
        file: "_content/pages/index.md"
        preview_path: "/"
        fields:
          - {label: path, name: path, widget: hidden, default: "index"}
          
          - label: "Sessão Como Funciona"
            name: feature
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Subtítulo", name: subtitle, widget: string}
          
          - label: "Sessão Outros Serviços"
            name: service
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Subtítulo", name: subtitle, widget: string}
          
          - label: "Contato"
            name: contact
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Subtítulo", name: subtitle, widget: text, required: false}

          - label: "SEO"
            name: seo
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}

          - label: "OpenGraph"
            name: opengraph
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}

              - label: "Imagem"
                name: image
                widget: "object"
                fields:
                  - {label: "Imagem", name: imageUrl, widget: image}
                  - {label: "Descrição da Imagem", name: imageAlt, widget: string}

  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
